[package]
name = "mz8086"
version = "0.1.0"
authors = ["Joshua Worth <joshua@worth.id.au>"]
edition = "2018"

[dependencies]
byteorder = "1.2.4"
num = "0.2.0"
num-derive = "0.2.2"
num-traits = "0.2.2"
